# Generated by Django 5.2 on 2025-04-27 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OKR',
            fields=[
                ('okr_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_okrs', to='okrapi.department')),
                ('parent_okr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_okrs', to='okrapi.okr')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='default_user', max_length=50, unique=True)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('hierarchy_path', models.CharField(max_length=255)),
                ('org_unit', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='okrapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('linked_to_okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='okrapi.okr')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='okrapi.user')),
            ],
        ),
        migrations.AddField(
            model_name='okr',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_okrs', to='okrapi.user'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=50)),
                ('confidence_level', models.IntegerField()),
                ('comment', models.TextField()),
                ('is_auto_generated', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='okrapi.okr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='okrapi.user')),
            ],
        ),
    ]
