# Generated by Django 5.2 on 2025-04-27 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='okr',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_okrs', to='okrapi.user'),
        ),
        migrations.CreateModel(
            name='OkrUserMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_mappings', to='okrapi.okr')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okr_mappings', to='okrapi.user')),
            ],
            options={
                'verbose_name': 'OKR User Assignment',
                'verbose_name_plural': 'OKR User Assignments',
                'unique_together': {('okr', 'user')},
            },
        ),
        migrations.AddField(
            model_name='okr',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_okrs_many', through='okrapi.OkrUserMapping', to='okrapi.user'),
        ),
    ]
