# Generated by Django 5.2 on 2025-04-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0002_alter_okr_assigned_to_okrusermapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='okr',
            name='assumptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
