# Generated by Django 5.2 on 2025-04-27 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0003_okr_assumptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('business_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('business_unit_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='BusinessUnitOKRMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='okr_mappings', to='okrapi.businessunit')),
                ('okr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_unit_mappings', to='okrapi.okr')),
            ],
            options={
                'unique_together': {('okr', 'business_unit')},
            },
        ),
        migrations.AddField(
            model_name='okr',
            name='business_units',
            field=models.ManyToManyField(related_name='okrs', through='okrapi.BusinessUnitOKRMapping', to='okrapi.businessunit'),
        ),
    ]
