# Generated by Django 5.2 on 2025-04-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0006_task_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='okr',
            name='isMeasurable',
            field=models.BooleanField(default=False),
        ),
    ]
