# Generated by Django 5.2 on 2025-04-28 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0009_taskchallenges_challenge_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='okr',
            name='assigned_to',
        ),
    ]
