# Generated by Django 5.2 on 2025-04-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0004_businessunit_alter_task_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'Completed'), (1, 'In Progress'), (2, 'Hold'), (3, 'Delayed'), (4, 'Yet to Start')], default=4),
        ),
    ]
