# Generated by Django 5.2 on 2025-04-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0005_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
    ]
