# Generated by Django 5.2 on 2025-04-28 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0007_okr_ismeasurable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='challenges',
        ),
        migrations.CreateModel(
            name='TaskChallenges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Yet to Start'), (1, 'Active'), (2, 'Discarded'), (3, 'Resolved')], default=0)),
                ('due_date', models.DateField()),
                ('remarks', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='okrapi.task')),
            ],
            options={
                'verbose_name': 'Task Challenge',
                'verbose_name_plural': 'Task Challenges',
            },
        ),
    ]
