# Generated by Django 5.2 on 2025-04-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okrapi', '0008_remove_task_challenges_taskchallenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskchallenges',
            name='challenge_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
